[package]
name = "find-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
ctrlc = "3.4.0"
regex = "^1.8.3"
terminal-link = "0.1.0"
